### ISSUE TITLE
Adopt unofficial extension?

### ISSUE THREAD

**Issue by edward-shen** [shlinkio/shlink-web-extension#1]
Hey @acelaya!

I've been personally testing out my [unofficial extension](https://github.com/edward-shen/shlink) and it looks like there's a few external users who have also been using it without any problems.

Is there any interest in adopting the repository? I'd be willing to transfer the repository to the shlinkio org and just continue maintaining it from there.

Let me know if you're interested. If not, no problem;  thought I'd just reach out in case you were.

**Comment by acelaya** [comment]
Hey @edward-shen.

Thanks for creating a tool that makes Shlink's ecosystem richer.

As per adopting it as official, I would prefer to keep things like they are for now.

Maintaining more projects is time consuming, and I don't have a lot of capacity.
